- components/bridge/index.js
- components/decimals-format/index.js
- components/navbar/index.js
- components/pool/info.js
- components/pools/pools.js
- components/transfer-status/index.js
- disable OP rewards
- show warning when estimated slippage > slippage
- check max pool balances on bridge ui
- fix token decimals for liquidity
- fix % share at my positions tab
> feat: fix miscellaneous issues

- components/bridge/index.js
- components/bridge/warning-gas-vs-amount.js
- package.json
- add select relayer fee asset type
- estimate relayer fee by asset type
- set relayer fee for xcall by asset type
- compare price of relayer fee and amount by symbol
> feat: relayer fee assets

- components/bridge/index.js
- components/select/chain/chains.js
- components/swap/index.js
- config/mainnet/chains.json
- lib/object/asset.js
- lib/object/balance.js
- lib/object/chain.js
- lib/object/contract.js
- lib/object/currency.js
- lib/object/pool.js
- handle direct link with disabled chain
> feat: pool & swap chain selection not disabled

- config/testnet/assets.json
https://github.com/connext/chaindata/pull/83
https://github.com/connext/monorepo/pull/4745
> Update RADAR data

- components/bridge/index.js
https://github.com/connext/monorepo/issues/4875
> feat: update xERC20 bridge additional details

- components/bridge/index.js
https://github.com/connext/monorepo/issues/4807
https://github.com/connext/monorepo/issues/4875
> feat: styling transfer message, change message

- components/bridge/index.js
- components/bridge/warning/xERC20.js
- trigger send after click complete transfer
- update balances after deposited to lockbox
> feat: update action for xERC20 asset

- components/bridge/index.js
- components/latest-transfers/index.js
https://github.com/connext/monorepo/issues/4954
> feat: check pending xERC20 transfers for popup complete transfer

- components/bridge/index.js
https://github.com/connext/monorepo/issues/5289
> fix: deliver alAsset unless receive local is specified

- .env
> fix: remove gnosis delay banner

- .env
fix: add gnosis warning banner
> fix: add gnosis warning banner

- .env
fix: remove gnosis warning banner
> fix: remove gnosis warning banner

- components/action-required/index.js
- components/bridge/index.js
- package.json
-  Added `signerAddress` param in the methods:
> Added signer Address for logs

- components/footer/index.js
- layout/index.js
- package.json
- yarn.lock
- Changed `sdk-core` to `sdk`, for the logs in DD.
> Changed the Connext package to sdk-server

- components/footer/index.js
- layout/index.js
- package.json
- yarn.lock
- Changed the sdk core to `sdk-server` package
> Changed to @connext/sdk2.2.2.alpha.7

- components/footer/index.js
- layout/index.js
- package.json
- yarn.lock
> fix: revert in sdk-core

- .env
- config/testnet/assets.json
- Updated lockbox address for esx token
> fix: lockbox address

- components/bridge/index.js
- components/transfer-status/index.js
- Added fix for time estimates for slow path transfer
> fix estimate slow path

- config/testnet/assets.json
- updated lockbox address in esx token
> fix: esx lockbox

- config/mainnet/assets.json
> feat: ezETH bnb

- .env
> chore: arb warning

- .env
> fix: remove warning

- config/mainnet/chains.json
config: rotate metis and eth public providers
> feat: rotate public providers
